apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kw5464ko8-go-gitops
  description: This is GitOps manifest for kw5464ko8-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: kw5464ko8-go
    backstage.io/kubernetes-id: kw5464ko8-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: kw5464ko8-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kw5464ko8-go
